class TulipStrategy(object):
    """Mealy transducer.

    Internal states are integers, the current state
    is stored in the attribute "state".
    To take a transition, call method "move".

    The names of input variables are stored in the
    attribute "input_vars".

    Automatically generated by tulip.dumpsmach on 2021-03-24 02:48:48 UTC
    To learn more about TuLiP, visit http://tulip-control.org
    """
    def __init__(self):
        self.state = 55
        self.input_vars = ['xobj']

    def move(self, xobj):
        """Given inputs, take move and return outputs.

        @rtype: dict
        @return: dictionary with keys of the output variable names:
            ['xcar', 'vcar']
        """
        output = dict()
        if self.state == 0:
            if (xobj == 1):
                self.state = 1

                output["xcar"] = 6
                output["vcar"] = 4
            else:
                self._error(xobj)
        elif self.state == 1:
            if (xobj == 1):
                self.state = 2

                output["xcar"] = 10
                output["vcar"] = 3
            else:
                self._error(xobj)
        elif self.state == 2:
            if (xobj == 1):
                self.state = 3

                output["xcar"] = 13
                output["vcar"] = 2
            else:
                self._error(xobj)
        elif self.state == 3:
            if (xobj == 1):
                self.state = 4

                output["xcar"] = 15
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 4:
            if (xobj == 1):
                self.state = 5

                output["xcar"] = 16
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 5:
            if (xobj == 1):
                self.state = 6

                output["xcar"] = 17
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 6:
            if (xobj == 1):
                self.state = 7

                output["xcar"] = 18
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 7:
            if (xobj == 1):
                self.state = 8

                output["xcar"] = 19
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 8:
            if (xobj == 1):
                self.state = 9

                output["xcar"] = 20
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 9:
            if (xobj == 1):
                self.state = 10

                output["xcar"] = 21
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 10:
            if (xobj == 1):
                self.state = 11

                output["xcar"] = 22
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 11:
            if (xobj == 1):
                self.state = 12

                output["xcar"] = 23
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 12:
            if (xobj == 1):
                self.state = 13

                output["xcar"] = 24
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 13:
            if (xobj == 1):
                self.state = 14

                output["xcar"] = 25
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 14:
            if (xobj == 1):
                self.state = 15

                output["xcar"] = 26
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 15:
            if (xobj == 1):
                self.state = 16

                output["xcar"] = 27
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 16:
            if (xobj == 1):
                self.state = 17

                output["xcar"] = 28
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 17:
            if (xobj == 1):
                self.state = 18

                output["xcar"] = 29
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 18:
            if (xobj == 1):
                self.state = 19

                output["xcar"] = 30
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 19:
            if (xobj == 1):
                self.state = 20

                output["xcar"] = 31
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 20:
            if (xobj == 1):
                self.state = 21

                output["xcar"] = 32
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 21:
            if (xobj == 1):
                self.state = 22

                output["xcar"] = 33
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 22:
            if (xobj == 1):
                self.state = 23

                output["xcar"] = 34
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 23:
            if (xobj == 1):
                self.state = 24

                output["xcar"] = 35
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 24:
            if (xobj == 1):
                self.state = 25

                output["xcar"] = 36
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 25:
            if (xobj == 1):
                self.state = 26

                output["xcar"] = 37
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 26:
            if (xobj == 1):
                self.state = 27

                output["xcar"] = 38
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 27:
            if (xobj == 1):
                self.state = 28

                output["xcar"] = 39
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 28:
            if (xobj == 1):
                self.state = 29

                output["xcar"] = 40
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 29:
            if (xobj == 1):
                self.state = 30

                output["xcar"] = 41
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 30:
            if (xobj == 1):
                self.state = 31

                output["xcar"] = 42
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 31:
            if (xobj == 1):
                self.state = 32

                output["xcar"] = 43
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 32:
            if (xobj == 1):
                self.state = 33

                output["xcar"] = 44
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 33:
            if (xobj == 1):
                self.state = 34

                output["xcar"] = 45
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 34:
            if (xobj == 1):
                self.state = 35

                output["xcar"] = 46
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 35:
            if (xobj == 1):
                self.state = 36

                output["xcar"] = 47
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 36:
            if (xobj == 1):
                self.state = 37

                output["xcar"] = 48
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 37:
            if (xobj == 1):
                self.state = 38

                output["xcar"] = 49
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 38:
            if (xobj == 1):
                self.state = 39

                output["xcar"] = 50
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 39:
            if (xobj == 1):
                self.state = 40

                output["xcar"] = 51
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 40:
            if (xobj == 1):
                self.state = 41

                output["xcar"] = 52
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 41:
            if (xobj == 1):
                self.state = 42

                output["xcar"] = 53
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 42:
            if (xobj == 1):
                self.state = 43

                output["xcar"] = 54
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 43:
            if (xobj == 1):
                self.state = 44

                output["xcar"] = 55
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 44:
            if (xobj == 1):
                self.state = 45

                output["xcar"] = 56
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 45:
            if (xobj == 1):
                self.state = 46

                output["xcar"] = 57
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 46:
            if (xobj == 1):
                self.state = 47

                output["xcar"] = 58
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 47:
            if (xobj == 1):
                self.state = 48

                output["xcar"] = 59
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 48:
            if (xobj == 1):
                self.state = 49

                output["xcar"] = 60
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 49:
            if (xobj == 1):
                self.state = 50

                output["xcar"] = 61
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 50:
            if (xobj == 1):
                self.state = 51

                output["xcar"] = 62
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 51:
            if (xobj == 1):
                self.state = 52

                output["xcar"] = 63
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 52:
            if (xobj == 1):
                self.state = 53

                output["xcar"] = 64
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 53:
            if (xobj == 1):
                self.state = 54

                output["xcar"] = 65
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 54:
            if (xobj == 1):
                self.state = 54

                output["xcar"] = 65
                output["vcar"] = 1
            else:
                self._error(xobj)
        elif self.state == 55:
            if (xobj == 1):
                self.state = 0

                output["xcar"] = 1
                output["vcar"] = 5
            else:
                self._error(xobj)
        else:
            raise Exception("Unrecognized internal state: " + str(self.state))
        return output

    def _error(self, xobj):
        raise ValueError("Unrecognized input: " + (
            "xobj = {xobj}; ").format(
                xobj=xobj))
