on:
  push:
    branches: ["*","!main"]

name: Pacti Development

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          enable-pep582: true
      - name: Install dependencies
        run: pdm install
      - name: Test code
        run: make test
