on:
  workflow_dispatch:
  # push:
  #   branches: ["*","!main"]

name: Pacti Development Review

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          enable-pep582: true
      - name: Install dependencies
        run: pdm install
      - name: Test code
        run: make test
      - name: Check types
        run: make check-types
      - name: Run linters on code
        run: make check-quality
      - name: Check types on Jupyter notebooks
        run: make check-jn-types
      - name: Run linters on Jupyter notebooks
        run: make check-jn-quality
      - name: Check documentation
        run: make check-docs
